services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-importer-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    networks:
      - users-importer-net

  db:
    image: mysql:8.0
    container_name: users-importer-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - users-importer-net

volumes:
  db-data:

networks:
  users-importer-net:
    driver: bridge
